spring:
  application:
    name: demo
  profiles:
    active: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 123

  jpa:
    open-in-view: false
    hibernate.ddl-auto: create

    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        jdbc.batch_size: 1000
        format_sql: true
        show_sql: true
        use_sql_comments: true