spring:
  application:
    name: demo
  profiles:
    active: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 123

  jpa:
    hibernate.ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
        jdbc.batch_size: 1000
